name: Sign & Release (auto from build)

on:
  workflow_run:
    workflows: ["Build Windows EXE (signed) + Release ZIP"]  # nom 'name:' du workflow build
    branches: [main]
    types: [completed]

permissions:
  actions: read
  contents: write

jobs:
  sign_and_release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    env:
      ARTIFACT_NAME: tauri-windows-exe   # <-- nom EXACT de l'artifact produit par le build

    steps:
      # 1) Télécharger l'artifact DU RUN QUI VIENT DE FINIR (pas besoin de run_id manuel)
      - name: Download artifact from triggering run
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ env.ARTIFACT_NAME }}
          if_no_artifact_found: fail

      # 2) Préparer la signature
      - name: Require signing secrets
        shell: pwsh
        run: |
          if (-not "${{ secrets.WINDOWS_CERTIFICATE }}" -or -not "${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}") {
            Write-Error "Missing secrets: WINDOWS_CERTIFICATE / WINDOWS_CERTIFICATE_PASSWORD"
          }

      - name: Decode PFX
        shell: pwsh
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
        run: |
          $ErrorActionPreference='Stop'
          New-Item -ItemType Directory -Force certificate | Out-Null
          Set-Content certificate\cert.b64 $env:WINDOWS_CERTIFICATE
          certutil -decode certificate\cert.b64 certificate\codesign.pfx | Out-Null

      - name: Resolve signtool.exe
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          $st = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe -ErrorAction SilentlyContinue |
            Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
          if (-not $st) {
            choco install windows-sdk-10-version-10.0.22621.0 -y --no-progress
            $st = Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse -Filter signtool.exe -ErrorAction SilentlyContinue |
              Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
          }
          if (-not $st) { Write-Error "signtool.exe not found." }
          "SIGNTOOL=$st" | Out-File -FilePath $env:GITHUB_ENV -Append

      # 3) Signer l'EXE
      - name: Locate EXE
        id: find
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          $exe = Get-ChildItem -Path . -Filter *.exe -Recurse | Sort-Object Length -Descending | Select-Object -First 1
          if (-not $exe) { Write-Error "No .exe found in downloaded artifact." }
          "exe=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "EXE => $($exe.FullName)"

      - name: Sign EXE (timestamp; RFC3161 then /t)
        shell: pwsh
        env:
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        run: |
          $ErrorActionPreference='Stop'
          $exe = "${{ steps.find.outputs.exe }}"
          $ok = $false
          $rfc = @("http://timestamp.digicert.com","http://timestamp.sectigo.com/rfc3161","http://rfc3161timestamp.globalsign.com/advanced")
          foreach ($u in $rfc) {
            & "$env:SIGNTOOL" sign /fd sha256 /f certificate\codesign.pfx /p "$env:WINDOWS_CERTIFICATE_PASSWORD" /tr $u /td sha256 /d "TauriKargo" "$exe"
            if ($LASTEXITCODE -eq 0) { $ok = $true; break } else { Write-Warning "RFC3161 failed: $u" }
          }
          if (-not $ok) {
            $legacy=@("http://timestamp.digicert.com","http://timestamp.sectigo.com","http://timestamp.globalsign.com/scripts/timestamp.dll")
            foreach ($u in $legacy) {
              & "$env:SIGNTOOL" sign /fd sha256 /f certificate\codesign.pfx /p "$env:WINDOWS_CERTIFICATE_PASSWORD" /t $u /d "TauriKargo" "$exe"
              if ($LASTEXITCODE -eq 0) { $ok = $true; break } else { Write-Warning "legacy /t failed: $u" }
            }
          }
          if (-not $ok) { Write-Error "All timestamp servers failed." }

      # 4) Construire release/ (EXE + ZIP avec exe dans bin/)
      - name: Build release/ (exe + zip)
        id: pack
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          Add-Type -AssemblyName System.IO.Compression.FileSystem

          # Tag & base liés AU RUN DU BUILD (évite 'latest' & cache CDN)
          $srcRun = "${{ github.event.workflow_run.id }}"
          $tag  = "run-$srcRun"
          $base = "TauriKargo-$srcRun"
          $title= "Signed build (source run $srcRun)"

          $ws = "${{ github.workspace }}"
          $relDir = Join-Path $ws "release"
          if (Test-Path $relDir) { Remove-Item $relDir -Recurse -Force }
          New-Item -ItemType Directory -Force $relDir | Out-Null

          $exeOut = Join-Path $relDir ($base + "-windows-x64.exe")
          Copy-Item -LiteralPath "${{ steps.find.outputs.exe }}" -Destination $exeOut -Force

          # ZIP 'safe': EXE dans bin/
          $root = Join-Path $relDir $base
          New-Item -ItemType Directory -Force $root | Out-Null
          $bin = Join-Path $root "bin"
          New-Item -ItemType Directory -Force $bin | Out-Null
          Copy-Item -LiteralPath $exeOut -Destination (Join-Path $bin (Split-Path $exeOut -Leaf)) -Force
          "See bin\$(Split-Path $exeOut -Leaf)" | Set-Content (Join-Path $root "README.txt")

          $zipOut = Join-Path $relDir ($base + "-windows-x64.zip")
          if (Test-Path $zipOut) { Remove-Item $zipOut -Force }
          [IO.Compression.ZipFile]::CreateFromDirectory($root, $zipOut, [IO.Compression.CompressionLevel]::Optimal, $true)

          "exe_rel=release/$(Split-Path $exeOut -Leaf)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "zip_rel=release/$(Split-Path $zipOut -Leaf)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "tag=$tag"   | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "title=$title"| Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "base=$base" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      # 5) (optionnel) Artifacts dans l’onglet Actions
      - name: Upload signed exe (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack.outputs.base }}-windows-x64.exe
          path: ${{ steps.pack.outputs.exe_rel }}
          if-no-files-found: error
          compression-level: 0

      - name: Upload signed zip (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack.outputs.base }}-windows-x64.zip
          path: ${{ steps.pack.outputs.zip_rel }}
          if-no-files-found: error
          compression-level: 0

      # 6) Release GitHub (softprops uniquement)
      - name: Create / Update Release (attach files)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.pack.outputs.tag }}
          name: ${{ steps.pack.outputs.title }}
          prerelease: false
          make_latest: true
          draft: false
          fail_on_unmatched_files: true
          files: |
            ${{ steps.pack.outputs.zip_rel }}
            ${{ steps.pack.outputs.exe_rel }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7) Liens
      - name: Summary (links)
        shell: pwsh
        run: |
          $tag  = "${{ steps.pack.outputs.tag }}"
          $repo = "${{ github.repository }}"
          $base = "${{ steps.pack.outputs.base }}"
          @(
            "# Release"
            "Tag : $tag"
            "ZIP : https://github.com/$repo/releases/download/$tag/$base-windows-x64.zip"
            "EXE : https://github.com/$repo/releases/download/$tag/$base-windows-x64.exe"
          ) | Set-Content -Path $env:GITHUB_STEP_SUMMARY -Encoding utf8
