name: Build Windows EXE (signed in CI)

on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

permissions: { contents: write }

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked --version ^1.6

      # Tes HTML sont dans src-tauri/assets → on les copie vers ./dist (attendu par tauri.conf.json -> ../dist)
      - name: Stage web assets to ./dist
        shell: pwsh
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          New-Item -ItemType Directory -Force dist | Out-Null
          Copy-Item src-tauri\assets\* dist -Recurse -Force
          if (-not (Test-Path dist\index.html)) { Write-Error "index.html missing in staged dist" }

      - name: Generate icons
        run: cargo tauri icon src-tauri/icon.png

      # Prépare signature (optionnelle)
      - name: Prepare code signing (optional)
        shell: pwsh
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        run: |
          if ($env:WINDOWS_CERTIFICATE -and $env:WINDOWS_CERTIFICATE_PASSWORD) {
            New-Item -ItemType Directory -Force certificate | Out-Null
            Set-Content certificate\cert.b64 $env:WINDOWS_CERTIFICATE
            certutil -decode certificate\cert.b64 certificate\codesign.pfx | Out-Null
            "TAURI_WIN_CERT_PATH=$(Resolve-Path certificate\codesign.pfx)" | Out-File -FilePath $env:GITHUB_ENV -Append
            "TAURI_WIN_CERT_PASS=$($env:WINDOWS_CERTIFICATE_PASSWORD)" | Out-File -FilePath $env:GITHUB_ENV -Append
            "GH_ARGS=--bundles app --config src-tauri/tauri.ci.json" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            "GH_ARGS=--bundles app" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      # Build: EXE portable uniquement; signé si secrets présents
      - name: Build portable EXE
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_WIN_CERT_PATH: ${{ env.TAURI_WIN_CERT_PATH }}
          TAURI_WIN_CERT_PASS: ${{ env.TAURI_WIN_CERT_PASS }}
        with:
          args: ${{ env.GH_ARGS }}

      - name: Upload artifacts (portable exe)
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-exe
          path: |
            src-tauri/target/release/bundle/app/**
            src-tauri/target/release/*.log
