name: Build Windows EXE (signed in CI)

on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }

permissions: { contents: write }

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked --version ^1.6

      # Tes HTML → ./dist (tauri.conf.json pointe vers ../dist)
      - name: Stage web assets to ./dist
        shell: pwsh
        run: |
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          New-Item -ItemType Directory -Force dist | Out-Null
          Copy-Item src-tauri\assets\* dist -Recurse -Force
          if (-not (Test-Path dist\index.html)) { Write-Error "index.html missing in staged dist" }

      - name: Generate icons
        run: cargo tauri icon src-tauri/icon.png

      # Certificat pour signature (optionnel)
      - name: Prepare code signing (optional)
        shell: pwsh
        env:
          WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}              # .pfx en base64
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
        run: |
          if ($env:WINDOWS_CERTIFICATE -and $env:WINDOWS_CERTIFICATE_PASSWORD) {
            New-Item -ItemType Directory -Force certificate | Out-Null
            Set-Content certificate\cert.b64 $env:WINDOWS_CERTIFICATE
            certutil -decode certificate\cert.b64 certificate\codesign.pfx | Out-Null
            "TAURI_WIN_CERT_PATH=$(Resolve-Path certificate\codesign.pfx)" | Out-File -FilePath $env:GITHUB_ENV -Append
            "TAURI_WIN_CERT_PASS=$($env:WINDOWS_CERTIFICATE_PASSWORD)" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      # Build portable EXE uniquement; signé si TAURI_WIN_CERT_* présents
      - name: Build portable EXE
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_WIN_CERT_PATH: ${{ env.TAURI_WIN_CERT_PATH }}
          TAURI_WIN_CERT_PASS: ${{ env.TAURI_WIN_CERT_PASS }}
          TAURI_BUNDLE_TARGETS: app   # force la cible app
        with:
          bundles: app                 # force côté action
          args: --config src-tauri/tauri.ci.json

      # Upload: on couvre les 2 emplacements possibles de l'exe
      - name: Upload artifacts (portable exe)
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-exe
          path: |
            src-tauri/target/release/bundle/app/*.exe
            src-tauri/target/release/TauriKargo*.exe
